execution=lambdatest
platformName=Android
automationName=UiAutomator2
deviceName=Pixel.*
platformVersion=9
isRealMobile=true
build=BDD-Mobile
name=Mobile Test
visual=true
lt.mobileHub=https://AsifATamboliext:LT_gBiJw242GlcX93aezKPJc6Qo8WJXg3uCv1hwskCYk8OQZom@mobile-hub.lambdatest.com/wd/hub
lt.username=AsifATamboliext
lt.accesskey=LT_gBiJw242GlcX93aezKPJc6Qo8WJXg3uCv1hwskCYk8OQZom
app=lt://APP1016045571754463339104694

#lt.mobileHub=https://gopikarajext:LT_qD7lJ2tJ3kuANmHqzIHvMcNHABnGZ33cGcMSINZn2BJuAfr@hub.lambdatest.com/wd/hub
#lt.username=gopikarajext
#lt.accesskey=LT_qD7lJ2tJ3kuANmHqzIHvMcNHABnGZ33cGcMSINZn2BJuAfr
#app=lt://APP10160572041754466309915255
