
execution=local
platformName=Android
deviceName=Pixel 3 XL
udid=8C4Y14R0E
#8C4Y14R0E
appPackage=com.adcb.bankSBX
appActivity=com.adcb.bankSBX.ADCBMIB
automationName=uiautomator2
appium.server=http://127.0.0.1:4723/wd/hub
adbPath=/Users/adcbkony/Library/Android/sdk/platform-tools/adb
# For LambdaTest remote execution, copy to android.lambdatest.properties and update app to lt://APP_ID
isRealMobile=true
#lt.mobileHub=https://<LT_USERNAME>:<LT_ACCESS_KEY>@mobile-hub.lambdatest.com/wd/hub
#lt.username=<LT_USERNAME>
#lt.accesskey=<LT_ACCESS_KEY>

