

execution=lambdatest
platformName=iOS
deviceName=iPhone 14
platformVersion=17
app=lt://APP_ID_IOS
isRealMobile=true
lt.mobileHub=https://<LT_USERNAME>:<LT_ACCESS_KEY>@mobile-hub.lambdatest.com/wd/hub
lt.username=<LT_USERNAME>
lt.accesskey=<LT_ACCESS_KEY>
